language: php

php:
  - 5.6
  - 7
  - 7.0
  - 7.1
  - 7.2
  - hhvm

sudo: false

install:
  - composer selfupdate
  - |
    if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then
      composer require 'codeclimate/php-test-reporter:*' 'satooshi/php-coveralls:*'
    else
      composer install
    fi

script:
  - composer travis

after_success:
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then test-reporter; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then coveralls -v; fi

matrix:
  allow_failures:
    - php: hhvm

addons:
  code_climate:
    repo_token: 88f6ac7c49cc25d18d61d853453edfab6ae37303ae26ecff3811e69682e8a6b0
